config/routes.rb
Rails.application.routes.draw do

  root 'parse#index'
  get 'dashboard' => 'parse#dashboard'
  get 'api_doc' => 'parse#api_doc'
  get 'error'=>'parse#error'
  get 'get_graph'=>'parse#get_graph'

  resources :users do 
    get 'sign_up',on: :collection
    get 'sign_in',on: :collection
    get 'sign_out',on: :collection
    post 'create_sign_up',on: :collection
    post 'create_sign_in',on: :collection
    get 'coin_rank',on: :collection
  end
  resources :coins do
    post 'coin_update',on: :member,as: :coin_update
  end
  resources :challanges do 
    post 'trigger_create',on: :collection,as: :trigger_create
    put 'trigger_update',on: :member,as: :trigger_update
    get 'get_coin_type',on: :collection
  end
  resources :tags do
    post 'create_tag',on: :collection,as: :create_tag
    put 'update_tag',on: :member,as: :update_tag
  end
  resources :histories do
    get 'history_coin_tag_rank',on: :collection
    put 'update_history',on: :member,as: :update_history
  end
end

app/controllers/parse_controller.rb
class ParseController < ApplicationController
	before_action :parse_authenticate
	before_action :set_coin,only: [:edit_coin,:update_coin]
	before_action :authenticate_user,except: [:index]
  before_action :set_user
  
	def index;end

  def api_doc;end
	
	def dashboard
		begin
			set_details
			set_graph(@coin_types.first) unless @coin_types.nil?
		rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired "
		rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		end
	end

	def get_graph
		if params[:coinType].blank?
			set_graph("Seven")
	  else
	  	graph_trigger = @parse_client.query("Challenges").tap do |q|
	        q.eq("creatorID",session[:object_id])
					q.eq("coinTypeName",params[:coinType])
			end.get
			@graph_triggers = graph_trigger.collect{|trigger| {date: (trigger["createdAt"]).to_time.strftime("%d"),
	                                                       amount: trigger["amountCoinsReward"]}}
			 respond_to do |format|
	     		format.js
	   	 end
	  end
  end

  private

  def set_details
    @coins = @parse_client.query("Coins").tap do |q|
        q.eq("creatorID",session[:object_id]) unless  @user["role_name"].eql?("User")
        q.eq("userID",session[:object_id]) if @user["role_name"].eql?("User")
    end.get.uniq{|x| x["cointTypeName"]}

    coin_type_details = @parse_client.query("CoinTypes").tap do |q|
      q.eq("creatorID",session[:object_id])
    end.get

    @coin_types = coin_type_details.collect{|coin_type| coin_type["cointTypeName"]}

    @triggers_details = @parse_client.query("Challenges").tap do |q|
      q.eq("creatorID",session[:object_id])
    end.get
  end
  
  def set_graph coin_type
    seven_triggers = @parse_client.query("Challenges").tap do |trigger|
        trigger.eq("creatorID",session[:object_id])
        trigger.eq("coinTypeName",coin_type)
      end.get
    @triggers = seven_triggers.collect{|trigger| {date: (trigger["createdAt"]).to_time.strftime("%d"),
                                                  amount: trigger["amountCoinsReward"]}}
  end

end

app/views/parse/_dashboard_tabs.html.erb
<ul class="nav nav-tabs" role="tablist" id="tabs-panel">
  <li role="presentation">
  	<%= link_to "Coin",dashboard_path %>
  </li>
  <li role="presentation">
  	<%= link_to "User",users_path,class: "user-click-tab" %>
  </li>
  <li role="presentation">
  	<%= link_to "Tags",tags_path%>
  </li>
  <li role="presentation">
  	<%= link_to "History",histories_path,class: "histories-click-tab" %>
  </li>
</ul>

<script type="text/javascript">
  $(document).ready(function(){
    $('li').each(function(){
      if(window.location.href.indexOf($(this).find('a:first').attr('href'))>-1){
        $(this).addClass('active').siblings().removeClass('active');}
    });
  });
</script>

app/views/parse/_get_graph.html.erb
<div id="morris-line-chart"></div>

<script type="text/javascript">
  $(function() {
    // Line Chart
    Morris.Line({
        // ID of the element in which to draw the chart.
        element: 'morris-line-chart',
         data: <%=raw graph_triggers.to_json%>,
        // The name of the data record attribute that contains x-amounts.
        xkey: 'date',
        // A list of names of data record attributes that contain y-amounts.
        ykeys: ['amount'],
        // Labels for the ykeys -- will be displayed when you hover over the
        // chart.
        labels: ['Amount'],
        xLabels: ['Date'],
        // Disables line smoothing
        smooth: false,
        resize: true,
        parseTime: false
    });
});
</script>

app/views/parse/_graph_checkbox.html.erb
<% unless @coin_types.nil? %>
  <% @coin_types.each do |coin_type| %>
  	<div class="checkbox">
  		<label>
  			<b><input type="checkbox" value="<%= coin_type %>" id="coin_type_check" class="coin_type_checkbox">
  				<%= coin_type %></b>
  		</label>
  	</div>
  <%end%>
<%else%>
  <h4>No data available</h4>
<%end%><br/>

<script type="text/javascript">
  $('input.coin_type_checkbox').on('change', function() {
    $('input.coin_type_checkbox').not(this).prop('checked', false);  
  });
</script>
<script type="text/javascript">
	$(document).ready(function(){
		$(".coin_type_checkbox").change(function(){
			$.ajax({
				method: "get",
				url: '/get_graph',
				data: {coinType: this.value}
			});
		});
	});
</script>

app/views/parse/_navbar.html.erb
<nav class="navbar navbar-inverse navbar-fixed-top nav-bar-main" role="navigation"> 
  <!-- Brand and toggle get grouped for better mobile display -->
  <div class="navbar-header">
    <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-ex1-collapse"> <span class="sr-only">Toggle navigation</span> <span class="icon-bar"></span> <span class="icon-bar"></span> <span class="icon-bar"></span> </button>
    <a class="navbar-brand" href="index.html"><img src="assets/logo.png" width="170"></a> </div>
  <!-- Top Menu Items -->
  <ul class="nav navbar-right top-nav" id="nav-top-right">
    <li class="dropdown"> <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= @user["email"] %><b class="caret"></b></a>
      <ul class="dropdown-menu">
        <li><%= link_to "Profile",user_path(session[:object_id]) %></li>
        <li class="divider"></li>
        <li><%= link_to "Log out",sign_out_users_path%></li>
      </ul>
    </li>
  </ul>
  <!-- Sidebar Menu Items - These collapse to the responsive navigation menu on small screens -->
  <div class="collapse navbar-collapse navbar-ex1-collapse">
    <ul class="nav navbar-nav side-nav">
      <li class="active"><%= link_to "Dashboard",dashboard_path %></li>
      <li><%= link_to "API",api_doc_path %></li>
      <li> <a href="#">q&a</a> </li>
      <li> <a href="#">Info</a> </li>
    </ul>
  </div>
  <!-- /.navbar-collapse --> 
</nav>

app/views/parse/dashboard.html.erb
<div id="wrapper"> 
  <!-- Navigation -->
  <%= render 'navbar'%>
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12"> 
          <div class="card">
            <%= render 'dashboard_tabs'%>
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane active" id="coin">
                <div class="content-block">
                  <div class="top-content">
                    <div class="col-md-10 col-xs-8 clear-box">
                      <%= link_to "Create Coin",new_coin_path,class: "btn create-coin-btn" unless @user["role_name"].eql?("User")%>
                    </div>
                    <div class="col-md-2 col-xs-4 clear-box"></div>
                  </div>
                  <%= render 'coins/index'%>
                </div>
                <% unless @user["role_name"].eql?("User")%>
                  <div class="content-block">
                    <div class="top-content">
                      <div class="col-md-2 col-xs4 clear-box">
                      </div>
                    </div>
                    <%= render 'coin_types/index'%>
                  </div>
                <%end%>
                <div class="content-block">
                  <div class="top-content">
                    <div class="col-md-10 col-xs-8 clear-box">
                      <%= link_to "Create Trigger",new_challange_path,class: "btn create-trigger-btn" unless @user["role_name"].eql?("User")%>
                    </div>
                    <div class="col-md-2 col-xs4 clear-box">
                    </div>
                  </div>
                  <%= render 'challanges/index'%>
                </div><br><br>
                <div class="content-block">
                  <div class="panel panel-default">
                    <div class="panel-heading">
                      <h3 class="panel-title"><i class="fa fa-bar-chart-o fa-fw"></i>Amount of Distributed Coins by Trigger</h3>
                    </div>
                    <div class="panel-body">
                      <%= render 'graph_checkbox'%>
                      <div id="line-chart">
                        <div id="morris-line-chart" data-value="<%= @triggers %>"></div>
                      </div>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

<script type="text/javascript">
  $(function() {
    Morris.Line({
        element: 'morris-line-chart',
         data: <%=raw @triggers.to_json%>,
        xkey: 'date',
        ykeys: ['amount'],
        labels: ['Amount'],
        xLabels: ['Date'],
        smooth: false,
        resize: true,
        parseTime: false
    });
});
</script>

app/views/parse/error.html.erb
<center><%= image_tag "404-error-page-not-found.png"%></center>

app/views/parse/get_graph.js.erb
$("#line-chart").html("<%= j(render 'get_graph',graph_triggers: @graph_triggers)%>")

app/views/parse/index.html.erb
<div style="float:right;margin-top: -2%;margin-right: 2%;;">
	<%= link_to "Sign Up",sign_up_users_path,class: "btn btn-primary" %> 
	<%= link_to "Log In",sign_in_users_path,class: "btn btn-primary" %> 
</div>