config/routes.rb
Rails.application.routes.draw do

  root 'parse#index'
  get 'dashboard' => 'parse#dashboard'
  get 'api_doc' => 'parse#api_doc'
  get 'error'=>'parse#error'
  get 'get_graph'=>'parse#get_graph'

  resources :users do 
    get 'sign_up',on: :collection
    get 'sign_in',on: :collection
    get 'sign_out',on: :collection
    post 'create_sign_up',on: :collection
    post 'create_sign_in',on: :collection
    get 'coin_rank',on: :collection
  end
  resources :coins do
    post 'coin_update',on: :member,as: :coin_update
  end
  resources :challanges do 
    post 'trigger_create',on: :collection,as: :trigger_create
    put 'trigger_update',on: :member,as: :trigger_update
    get 'get_coin_type',on: :collection
  end
  resources :tags do
    post 'create_tag',on: :collection,as: :create_tag
    put 'update_tag',on: :member,as: :update_tag
  end
  resources :histories do
    get 'history_coin_tag_rank',on: :collection
    put 'update_history',on: :member,as: :update_history
  end
end

app/models/user.rb
class User < ActiveRecord::Base
  # has_attached_file :imgQrCode
  # validates_attachment_content_type :imgQrCode, content_type: /\Aimage\/.*\Z/
  # has_attached_file :photo
  # validates_attachment_content_type :photo, content_type: /\Aimage\/.*\Z/
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
	before_action :parse_authenticate
	before_action :authenticate_user,except: [:sign_up,:sign_in,:create_sign_up,:create_sign_in]
	before_action :set_user,except: [:sign_up,:sign_in,:create_sign_up,:create_sign_in]
	before_action :find_user,only: [:show,:destroy]
	before_action :user_params,only: [:create,:create_sign_up]
	before_action :set_roles,only: [:new,:sign_up]
	before_action :set_user_details,only: [:index]

	include ParseParams

	def new;end

	def create;end

	def show;end

	def sign_up;end

	def sign_in;end

	def sign_out
		session["object_id"] = nil
  	redirect_to sign_in_users_path
	end

	def create_sign_up;end

	def create_sign_in
		begin
		  user = Parse::User.authenticate(params[:username],params[:password], @parse_client)
		  session[:object_id] = user["objectId"]
	  	redirect_to dashboard_path
		rescue Parse::ParseProtocolError => e
		 	flash[:error] = "Invalid username or password"
		 	redirect_to :back
	  rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		 	redirect_to :back
		end
	end
	
	def index;end

	def coin_rank
		if params[:coinType].blank?
  		set_coin_rank("ZBB")
  	else
  	@ranking_coins = set_coin_rank(params[:coinType])
	  	respond_to do |format|
		     format.js
		  end
  	end
	end

	private
	
	def user_params
		@user_params = params[:user]
		save_imgqrcode
		save_photo
		save_user_params
		@user.save
		redirect_to user_path(@user["objectId"])
	end

	def find_user
		begin
  		@user = @parse_client.query("_User").eq("objectId", params[:id]).get.first
  	rescue Parse::ConnectionError => e
	 		flash[:error] = "ConnectionError"
			redirect_to dashboard_path
	  rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired"
			redirect_to dashboard_path
		end
	end

	def set_roles
		@roles = ["Admin","Issuer","User"]
	end

	def set_user_details
		coins_users = @parse_client.query("Coins").tap do |q|
			q.eq("creatorID",session[:object_id])
		end.get.collect{|coin| coin["userID"]}
		coins_users.find_all{|e| coins_users.count(e) > 1}   
   	coins_users ? @coins_users = coins_users.uniq! : @coins_users = coins_users
		@coin_types = coin_type_details = @parse_client.query("CoinTypes").tap do |q|
      q.eq("creatorID",session[:object_id])
    end.get.collect{|coin_type| coin_type["cointTypeName"]}

    @ranking_coins = set_coin_rank(@coin_types.first) unless @coin_types.blank?
	end

	def set_coin_rank coin_type
		ranking_coins = @parse_client.query("Coins").tap do |coin|
	  	coin.eq("cointTypeName",coin_type) 
    end.get 
    ranking_amount = ranking_coins.map{|coin| [coin["userID"],coin["totalAmountPoints"]]}
		ranking_list = ranking_amount.collect{|id,amount| {userid: id,total_amount: amount.to_i}}
		ranking_list.sort_by{|hash| hash[:total_amount]}.reverse!
	end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_coin_rank_details.html.erb
<table class="table table-hover table-striped details-table coin-tab-table" id="coin_rank_table">
  <thead>
    <tr>
      <th>Ranking</th>
      <th class="action">User Name</th>
      <th class="action">Amount</th>
    </tr>
  </thead>
  <% unless @ranking_coins.blank? %>
    <% @ranking_coins.each_with_index do |rank,index|%>
    <tbody>
      <tr>
        <td><%= index+1 %></td>
        <td><%= rank_user(rank[:userid])%></td>
        <td><%= rank[:total_amount]%></td>
      </tr>
    </tbody>
    <%end%>
  <%end%>
</table>

app/views/users/_index.html.erb
<table class="table table-hover table-striped details-table history-tab-table" id="user_table">
  <thead>
    <tr>
      <th class="action">Photo</th>
      <th class="action">User Name</th>
      <th class="action">Profile Name</th>
      <th>Created At</th>
      <th>Bitcoin Address</th>
      <th class="action">CoinSpark Address</th>
      <!-- <th>Coin Amount</th> -->
    </tr>
  </thead>
  <tbody>
   <% unless @user["role_name"].eql?("User") %>
    <% unless @coins_users.blank? %>
      <% @coins_users.each do |user|%>
        <% get_user(user) %>
        <tr>
          <td><%= image_tag @coin_user["photoUrl"],style: "width: 30%;" rescue nil %></td>
          <td><%= @coin_user["username"]%></td>
          <td><%= @coin_user["profileName"]%></td>
          <td><%= (@coin_user["createdAt"]).to_time.strftime("%d %b %Y") %></td>
          <td><%= @coin_user["bitcoinAddress"]%></td>
          <td><%= @coin_user["coinsparkAddress"]%></td>
        </tr>
      <%end%>
    <%end%>
   <%else%>
    <tr>
      <td><%= image_tag @user["photoUrl"],style: "width: 53%;" rescue nil %></td>
      <td><%= @user["username"]%></td>
      <td><%= @user["profileName"]%></td>
      <td><%= (@user["createdAt"]).to_time.strftime("%d %b %Y") %></td>
      <td><%= @user["bitcoinAddress"]%></td>
      <td><%= @user["coinsparkAddress"]%></td>
    </tr>
   <%end%>
  </tbody>
</table>

app/views/users/coin_rank.js.erb
$("#coin_rank").html("<%= j(render 'coin_rank_details')%>")

app/views/users/index.html.erb
<div id="wrapper"> 
  <!-- Navigation -->
  <%= render 'parse/navbar'%>
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12"> 
          <div class="card">
            <%= render 'parse/dashboard_tabs'%>
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane" id="user">
                <div class="content-block">
                  <div class="top-content">
                    <div class="col-md-10 col-xs-8 clear-box">
                      <%= link_to "Create User",new_user_path,class: "btn create-user-btn" unless @user["role_name"].eql?("User")%>
                    </div>
                    <div class="col-md-2 col-xs-4 clear-box">
                    </div>
                  </div>
                  <%= render 'index'%>
                </div>
                <div class="content-block">
                  <div class="col-md-6">
                    <h2>Coin & Tag Base ranking</h2><br><br>
                    <%= select_tag 'cointype', options_for_select(@coin_types.collect{ |u| u},selected: "ZBB"),class: "cointype_select btn btn-default green-drop" unless @coin_types.nil? %><br><br>
                    <div class="clearfix"></div>
                    <div id="coin_rank">
                      <%= render 'coin_rank_details'%>
                    </div>
                  </div>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

<style type="text/css">
  .tab-content>.tab-pane{
    display: block !important;
  }
</style>

<script type="text/javascript">
  $(document).ready(function(){
    $(".cointype_select").change(function(){
      $.ajax({
        method: 'get',
        url: '/users/coin_rank',
        data: {coinType: this.value}
      });
    });
  });
</script>

app/views/users/new.html.erb
<div class="container">
 <div class="col-md-10">
  <%= form_for(User.new) do |f|%>
    <div class="form-group">
      <label for="username">username</label>
      <%= f.text_field :username, class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="profilename">profileName</label>
      <%= f.text_field :profileName,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="playerIdForPush">playerIdForPush</label>
      <%= f.text_field :playerIdForPush,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="coinsparkAddress">coinsparkAddress</label>
      <%= f.text_field :coinsparkAddress,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="bitcoinAddress">bitcoinAddress</label>
      <%= f.text_field :bitcoinAddress,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="bitcoinPassword">bitcoinPassword</label>
      <%= f.text_field :bitcoinPassword,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="imgQrCode">imgQrCodeUrl</label>
      <%= f.file_field :imgQrCode,required: :true%>
    </div>
    <div class="form-group">
      <label for="photo">photoUrl</label>
      <%= f.file_field :photo,required: :true%>
    </div>
    <div class="form-group">
      <label for="role_type">role_name</label>
      <%= select_tag 'role_type', options_for_select(@roles.collect{ |u| u}),class: "form-control",required: :true %>
    </div>
    <div class="form-group">
      <label for="phone">phone</label>
      <%= f.text_field :phone,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="email">email</label>
      <%= f.email_field :email,class: "form-control",required: :true%>
    </div>
    <div class="form-group">
      <label for="password">password</label>
      <%= f.password_field :password,class: "form-control",required: :true%>
    </div>
    <%= f.submit "Sign Up",class: "btn btn btn-primary"%>
    <%= link_to "Back",dashboard_path,class: "btn btn-warning"%>
  <%end%>
  </div>
</div>
<br><br>

app/views/users/show.html.erb
<div class="container">
	<h3>User</h3>
	<p>
		<strong>ObjectId:</strong>
		<%= @user["objectId"]%>
	</p>
	<p>
		<strong>playerIdForPush:</strong>
		<%= @user["playerIdForPush"]%>
	</p>
	<p>
		<strong>coinsparkAddress:</strong>
		<%= @user["coinsparkAddress"]%>
	</p>
	<p>
		<strong>profileName:</strong>
		<%= @user["profileName"]%>
	</p>
	<p>
		<strong>username:</strong>
		<%= @user["username"]%>
	</p>
	<p>
		<strong>bitcoinPassword:</strong>
		<%= @user["bitcoinPassword"]%>
	</p>
	<p>
		<strong>imgQrCodeUrl:</strong><br><br>
		<%= image_tag @user["imgQrCodeUrl"],style: "width: 20%" rescue nil%>
	</p>
	<p>
		<strong>photoUrl:</strong><br><br>
		<%= image_tag @user["photoUrl"],style: "width: 20%" rescue nil%>
	</p>
	<p>
		<strong>rolename:</strong>
		<%= @user["role_name"]%>
	</p>
	<p>
		<strong>email:</strong>
		<%= @user["email"]%>
	</p>
	<p>
		<strong>phone:</strong>
		<%= @user["phone"]%>
	</p>
	<p>
		<strong>createdAt:</strong>
		<%= (@user["createdAt"]).to_time.strftime("%d %b %Y")%>
	</p>
	<p>
		<strong>updatedAt:</strong>
		<%= (@user["updatedAt"]).to_time.strftime("%d %b %Y")%>
	</p><br><br>
	<%= link_to "Dashboard",dashboard_path,class: "btn btn-warning"%>
</div>
<br><br>

app/views/users/sign_in.html.erb
<div class="container">
  <div class="row">

    <div class="main">

      <h3>Please Login , or <a href="<%= sign_up_users_path %>">Sign Up</a></h3>
      <div class="row"></div>
      <div class="login-or">
        <hr class="hr-or">
        <span class="span-or">or</span>
      </div>
      <%= form_tag create_sign_in_users_path,method: "post" do %>
        <div class="form-group">
          <label for="inputUsername">Username</label>
          <%= text_field_tag "username",nil,class: "form-control"%>
        </div>
        <div class="form-group">
          <!-- <a class="pull-right" href="#">Forgot password?</a> -->
          <label for="inputPassword">Password</label>
          <%= password_field_tag "password",nil,class: "form-control"%>
        </div>
        <%= submit_tag "Log In",class: "btn btn btn-primary"%>
      <%end%>
    </div>
    
  </div>
</div>

app/views/users/sign_up.html.erb
<div class="">
  <div class="">
    <div class="main">
      <h3>Please Sign Up, or <a href="<%= sign_in_users_path %>">Sign In</a></h3>
      <div class="login-or">
        <hr class="hr-or">
        <span class="span-or">or</span>
      </div>
      <%= form_for(User.new,url: create_sign_up_users_path) do |f|%>
        <div class="form-group">
          <label for="username">username</label>
          <%= f.text_field :username, class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="profilename">profileName</label>
          <%= f.text_field :profileName,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="playerIdForPush">playerIdForPush</label>
          <%= f.text_field :playerIdForPush,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="coinsparkAddress">coinsparkAddress</label>
          <%= f.text_field :coinsparkAddress,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="bitcoinAddress">bitcoinAddress</label>
          <%= f.text_field :bitcoinAddress,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="bitcoinPassword">bitcoinPassword</label>
          <%= f.text_field :bitcoinPassword,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="imgQrCode">imgQrCodeUrl</label>
          <%= f.file_field :imgQrCode,required: :true%>
        </div>
        <div class="form-group">
          <label for="photo">photoUrl</label>
          <%= f.file_field :photo,required: :true%>
        </div>
        <div class="form-group">
            <label for="role_type">rolename</label>
            <%= select_tag 'role_type', options_for_select(@roles.collect{ |u| u}),class: "form-control",required: :true %>
        </div>
        <div class="form-group">
          <label for="phone">phone</label>
          <%= f.text_field :phone,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="email">email</label>
          <%= f.email_field :email,class: "form-control",required: :true%>
        </div>
        <div class="form-group">
          <label for="password">password</label>
          <%= f.password_field :password,class: "form-control",required: :true%>
        </div>
        <%= f.submit "Sign Up",class: "btn btn btn-primary"%>
      <%end%>
    </div>
  </div>
</div><br><br>