config/routes.rb
Rails.application.routes.draw do

  root 'parse#index'
  get 'dashboard' => 'parse#dashboard'
  get 'api_doc' => 'parse#api_doc'
  get 'error'=>'parse#error'
  get 'get_graph'=>'parse#get_graph'

  resources :users do 
    get 'sign_up',on: :collection
    get 'sign_in',on: :collection
    get 'sign_out',on: :collection
    post 'create_sign_up',on: :collection
    post 'create_sign_in',on: :collection
    get 'coin_rank',on: :collection
  end
  resources :coins do
    post 'coin_update',on: :member,as: :coin_update
  end
  resources :challanges do 
    post 'trigger_create',on: :collection,as: :trigger_create
    put 'trigger_update',on: :member,as: :trigger_update
    get 'get_coin_type',on: :collection
  end
  resources :tags do
    post 'create_tag',on: :collection,as: :create_tag
    put 'update_tag',on: :member,as: :update_tag
  end
  resources :histories do
    get 'history_coin_tag_rank',on: :collection
    put 'update_history',on: :member,as: :update_history
  end
end

app/controllers/tags_controller.rb
class TagsController < ApplicationController
	before_action :parse_authenticate
	before_action :authenticate_user
	before_action :set_user
	before_action :set_tag,only: [:edit,:update_tag,:destroy,:show]
	before_action :tag_params,only: [:create_tag,:update_tag]
	before_action :coin_type_details,only: [:new,:edit]
	before_action :set_tag_details,only: [:index]
	
	include ParseParams

	def new;end

	def create_tag;end

	def edit;end

	def update_tag;end

	def show;end
	
	def destroy;end

	def index;end

	private 

  def tag_params
		begin
	  	params[:action].eql?("create_tag") ? 
	  	@tag = @parse_client.object("HashTags") : @tag = @tag
	  	save_params
			redirect_to tag_path(@tag["objectId"])
	  rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired"
		 	redirect_to error_path
		rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		 	redirect_to error_path
		end
  end

  def save_params
  	save_tag_params
		@tag.save
  end

  def set_tag
  	tag = @parse_client.query("HashTags")		
  	@tag = tag.eq("objectId", params[:id]).get.first
  end

  def coin_type_details

  	coin_type_details = @parse_client.query("CoinTypes").tap do |q|
      q.eq("creatorID",session[:object_id])
    end.get

    @coin_types = coin_type_details.collect{|coin_type| coin_type["objectId"]}

  	@users = @parse_client.query("_User").tap do |user|
  		 user.eq("role_name","User")
  	end.get

  	@user_names = @users.collect{|user| user["username"]}

  end
  
  def set_tag_details
  	@hash_tags_details = @parse_client.query("HashTags").tap do |q|
  		q.eq("creatorID",session[:object_id])
  	end.get
  end
end

app/helpers/tags_helper.rb
module TagsHelper
end

app/views/tags/_index.html.erb
<table class="table table-hover table-striped details-table history-tab-table" id="hash_tag_table">
  <thead>
    <tr>
      <th class="action">Tag Name</th>
      <th class="action">Taged Coin</th>
      <th class="action">Taged User</th>
      <th>Sent At</th>
      <th>Total Amount</th>
      <th class="action">CoinSpark Address</th>
      <!-- <th>Total Amount</th> -->
      <th class="action">Actions</th>
    </tr>
  </thead>
  <tbody>
    <% @hash_tags_details.each do |hash_tag|%>
      <tr>
        <td><%= hash_tag["TagName"]%></td>
        <td><%= set_tag(hash_tag["coinTypeObjectID"])%></td>
        <td><%= hash_tag["UserName"]%></td>
        <td><%= (hash_tag["createdAt"]).to_time.strftime("%b %d %Y")%></td>
        <td><%= hash_tag["totalAmountPoints"]%></td>
        <td><%= find_user(hash_tag["userID"]) rescue nil%></td>
        <!-- <td></td> -->
        <td>
          <%= link_to "Edit",edit_tag_path(hash_tag["objectId"]),class: "btn edit-btn"%>
        </td>
      </tr>
    <%end%>
  </tbody>
</table>

app/views/tags/edit.html.erb
<div class="container">
  <div class="col-md-10">
    <h3>Edit Tag</h3>
    <%= form_tag update_tag_tag_path(@tag["objectId"]),method: "put" do %>
      <div class="form-group">
        <label for="TagName">TagName</label>
        <%= text_field_tag "TagName",nil,class: "form-control",value: @tag["TagName"],required: :true%>
      </div>
      <div class="form-group">
        <label for="coinTypeObjectID">coinTypeObjectID</label>
        <%= select_tag 'coinTypeObjectID',options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="userID">userID</label>
        <%= select_tag 'userID',options_for_select(@users.collect{ |u| u["objectId"]}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="creatorID">creatorID</label>
        <%= text_field_tag "creatorID",nil,class: "form-control",value: @user["objectId"],readonly: true%>
      </div>
      <div class="form-group">
        <label for="username">UserName</label>
        <%= select_tag 'username',options_for_select(@user_names.collect{ |u| u}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="totalAmountPoints">totalAmountPoints</label>
        <%= text_field_tag "totalAmountPoints",nil,class: "form-control",value: @tag["totalAmountPoints"],required: :true%>
      </div>
      <%= submit_tag "Update Tag",class: "btn btn-primary"%>
      <%= link_to "Back",dashboard_path,class: "btn btn-warning"%>
    <%end%>
  </div>
</div>

app/views/tags/index.html.erb
<div id="wrapper"> 
  <!-- Navigation -->
  <%= render 'parse/navbar'%>
  <div id="page-wrapper">
    <div class="container-fluid">
      <div class="row">
        <div class="col-md-12"> 
          <div class="card">
            <%= render 'parse/dashboard_tabs'%>
            <div class="tab-content">
              <div role="tabpanel" class="tab-pane" id="tag">
                <div class="content-block">
                  <div class="top-content">
                    <div class="col-md-10 col-xs-8 clear-box">
                      <%= link_to "Create Tags",new_tag_path,class: "btn create-tag-btn"%>
                    </div>
                    <div class="col-md-2 col-xs-4 clear-box">
                    </div>
                  </div>
                  <%= render 'index'%>
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div> 
  </div>
</div>

<style type="text/css">
  .tab-content>.tab-pane{
    display: block !important;
  }
</style>

app/views/tags/new.html.erb
<div class="container">
  <div class="col-md-10">
    <h3>New Tag</h3>
    <%= form_tag create_tag_tags_path,method: "post" do %>
      <div class="form-group">
        <label for="TagName">TagName</label>
        <%= text_field_tag "TagName",nil,class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="coinTypeObjectID">coinTypeObjectID</label>
        <%= select_tag 'coinTypeObjectID',options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="userID">userID</label>
        <%= select_tag 'userID',options_for_select(@users.collect{ |u| u["objectId"]}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="creatorID">creatorID</label>
        <%= text_field_tag "creatorID",nil,class: "form-control",value: @user["objectId"],readonly: true%>
      </div>
      <div class="form-group">
        <label for="username">UserName</label>
        <%= select_tag 'username',options_for_select(@user_names.collect{ |u| u}),prompt: "Select",class: "form-control"%>
      </div>
      <div class="form-group">
        <label for="totalAmountPoints">totalAmountPoints</label>
        <%= text_field_tag "totalAmountPoints",nil,class: "form-control"%>
      </div>
      <%= submit_tag "Create Tag",class: "btn btn-default"%>
    <%end%>
  </div>
</div>

app/views/tags/show.html.erb
<div class="container">
	<h3>Tag</h3>
	<p>
		<strong>ObjectId:</strong>
		<%= @tag["objectId"]%>
	</p>
	<p>
		<strong>TagName:</strong>
		<%= @tag["TagName"]%>
	</p>
	<p>
		<strong>coinTypeObjectID:</strong>
		<%= @tag["coinTypeObjectID"]%>
	</p>
	<p>
		<strong>userID:</strong>
		<%= @tag["userID"]%>
	</p>
	<p>
		<strong>creatorID:</strong>
		<%= @tag["creatorID"]%>
	</p>
	<p>
		<strong>UserName:</strong>
		<%= @tag["UserName"]%>
	</p>
	<p>
		<strong>totalAmountPoints:</strong>
		<%= @tag["totalAmountPoints"]%>
	</p><br><br>
	<%= link_to "Dashboard",dashboard_path,class: "btn btn-warning"%>
</div>