config/routes.rb
Rails.application.routes.draw do

  root 'parse#index'
  get 'dashboard' => 'parse#dashboard'
  get 'api_doc' => 'parse#api_doc'
  get 'error'=>'parse#error'
  get 'get_graph'=>'parse#get_graph'

  resources :users do 
    get 'sign_up',on: :collection
    get 'sign_in',on: :collection
    get 'sign_out',on: :collection
    post 'create_sign_up',on: :collection
    post 'create_sign_in',on: :collection
    get 'coin_rank',on: :collection
  end
  resources :coins do
    post 'coin_update',on: :member,as: :coin_update
  end
  resources :challanges do 
    post 'trigger_create',on: :collection,as: :trigger_create
    put 'trigger_update',on: :member,as: :trigger_update
    get 'get_coin_type',on: :collection
  end
  resources :tags do
    post 'create_tag',on: :collection,as: :create_tag
    put 'update_tag',on: :member,as: :update_tag
  end
  resources :histories do
    get 'history_coin_tag_rank',on: :collection
    put 'update_history',on: :member,as: :update_history
  end
end

app/controllers/challanges_controller.rb
class ChallangesController < ApplicationController
	before_action :parse_authenticate
	before_action :authenticate_user
	before_action :set_user
	before_action :set_trigger,only: [:edit,:trigger_update,:destroy,:show]
	before_action :trigger_params,only: [:trigger_create,:trigger_update]
	before_action :set_coin_details,only: [:new,:edit]

	include ParseParams

	def new;end

	def trigger_create;end

	def edit;end

	def show;end

	def trigger_update;end

	def destroy
		begin
			@trigger.parse_delete
			redirect_to dashboard_path
		rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired "
		 	redirect_to error_path
		rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		 	redirect_to error_path
		end
	end

	def get_coin_type
		cointype = @parse_client.query("CoinTypes")	
		@cointype = cointype.eq("objectId", params[:coinTypeId]).get.first
		respond_to do |format|
			format.js
		end
	end

	private

	def trigger_params
		params[:action].eql?("trigger_create") ? 
		@trigger = @parse_client.object("Challenges") : @trigger = @trigger
		save_trigger_params
  	@trigger.save
  	redirect_to challange_path(@trigger["objectId"])
  end

  def set_coin_details
  	begin
	  	coins = @parse_client.query("Coins").tap do |coin|
	      coin.eq("creatorID",session[:object_id])
	  	end.get
	  	tags = @parse_client.query("HashTags").tap do |tag|
	      tag.eq("creatorID",session[:object_id])
	  	end.get

	  	hash_tags = tags.collect{|tag| tag["TagName"]}
	  	tag = hash_tags.find_all{|e| hash_tags.count(e) > 1} 
	  	tag.present? ? @tags = hash_tags.uniq! : @tags = hash_tags

	  	coin_types = @parse_client.query("CoinTypes").tap do |coin|
	      coin.eq("creatorID",session[:object_id])
	  	end.get

	  	@coin_types = coin_types.collect{|coin_type| coin_type["objectId"]}
	  	@coins = coins.collect{|coin| coin["objectId"]}
	  	@status_types = ["Complete","Incomplete"]
	  	@repeat_amounts = ["10","20","30","40","50","100","500","1000"]
	  rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired "
		 	redirect_to error_path
		rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		 	redirect_to error_path
		end
  end

  def set_trigger
  	begin
  		trigger = @parse_client.query("Challenges")		
  		@trigger = trigger.eq("objectId", params[:id]).get.first
  	rescue Parse::ParseProtocolError => e
		 	flash[:error] = "server execution time expired "
		 	redirect_to error_path
		rescue Parse::ConnectionError => e
		 	flash[:error] = "ConnectionError"
		 	redirect_to error_path
		end
  end
end

app/helpers/challanges_helper.rb
module ChallangesHelper
end

app/views/challanges/_get_coin_type.html.erb
<% if params[:type].eql?("Coin")%>
  <div class="form-group">
    <label for="coinTypeName">coinTypeName</label>
	  <%= text_field_tag "coinTypeName",nil,class: "form-control",required: :true,value: @cointype["cointTypeName"],readonly: true%>
  </div>
<%elsif params[:type].eql?("coinTypeObject")%>
  <div class="form-group">
    <label for="cointTypeName">cointTypeName</label>
    <%= text_field_tag "coin[cointTypeName]",nil,class: "form-control",value: @cointype["cointTypeName"],readonly: true%>
  </div>
<%else%>
	<div class="form-group">
	  <label for="rewardCoinTypeName">rewardCoinTypeName</label>
	  <%= text_field_tag "rewardCoinTypeName",nil,class: "form-control",required: :true,value: @cointype["cointTypeName"],readonly: true%>
	</div>
<%end%>

app/views/challanges/_index.html.erb
<% if @user["role_name"].eql?("User")%>
  <h2>Triggers</h2><br>
<%end%>
<div>
  <table class="table table-hover table-striped details-table coin-tab-table" id="trigger_table">
    <thead>
      <tr>
        <th class="action">Reward Coin</th>
        <th class="action">Tags</th>
        <th>Expire Date</th>
        <th>Created At</th>
        <th class="action">Points for Period</th>
        <th class="action">Period</th>
        <th class="action">Actions</th>
      </tr>
    </thead>
    <% if !(@triggers_details.nil?) %>
      <% @triggers_details.each do |trigger|%>
        <tbody>
          <tr>
            <td><%= trigger["rewardCoinTypeName"]%></td>
            <td><%= trigger["tags"]%></td>
            <td><%= trigger["expiryDate"]%></td>
            <td><%= (trigger["createdAt"]).to_time.strftime("%d %b %y")%></td>
            <td><%= trigger["numberOfRepeat"]%></td>
            <td><%= trigger["period"]%></td>
            <td>
              <%= link_to "Edit",edit_challange_path(trigger["objectId"]),class: "btn edit-btn"%>
              <%= link_to 'Delete', challange_path(trigger["objectId"]),method: :delete, :data => {:confirm => 'Are you sure?'},class: "btn delete-btn" %>
            </td>
          </tr>
        </tbody>
      <%end%>
    <%end%>
  </table>
</div>

app/views/challanges/edit.html.erb
<div class="container">
  <div class="col-md-10">
    <h3>Edit Trigger</h3>
    <%= form_tag trigger_update_challange_path(@trigger["objectId"]),method: "put" do %>
      <div class="form-group">
        <label for="period">period</label>
        <%= text_field_tag "period",nil,class: "form-control",value: @trigger["period"],required: :true%>
      </div>
      <div class="form-group">
        <label for="actionName">actionName</label>
        <%= text_field_tag "actionName",nil,class: "form-control",value: @trigger["actionName"],required: :true%>
      </div>
      <div class="form-group">
        <label for="expiryDate">expiryDate</label>
        <%= text_field_tag "expiryDate",nil,class: "trigger_datepicker form-control",value: @trigger["expiryDate"],required: :true%>
      </div>
      <div class="form-group">
        <label for="rewardCoinTypeID">rewardCoinTypeID</label>
        <%= select_tag 'rewardCoinTypeID', options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div id="rewardcointypename">
        <div class="form-group">
          <label for="rewardCoinTypeName">rewardCoinTypeName</label>
          <%= text_field_tag "rewardCoinTypeName",nil,class: "form-control",required: :true,value: @trigger["rewardCoinTypeName"]%>
        </div>
      </div>
      <div class="form-group">
        <label for="coinTypeID">coinTypeID</label>
        <%= select_tag 'coinTypeID', options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div id="cointypename">
        <div class="form-group">
          <label for="coinTypeName">coinTypeName</label>
          <%= text_field_tag "coinTypeName",nil,class: "form-control",required: :true,value: @trigger["coinTypeName"]%>
        </div>
      </div>
   
      <div class="form-group">
        <label for="creatorID">creatorID</label>
        <%= text_field_tag "creatorID",nil,class: "form-control",value: @user["objectId"],readonly: true,required: :true%>
      </div>
      <div class="form-group">
        <label for="groupName">groupName</label>
        <%= text_field_tag "groupName",nil,class: "form-control",value: @trigger["groupName"],required: :true%>
      </div>
      <div class="form-group">
        <label for="coinID">coinID</label>
        <%= select_tag 'coinID', options_for_select(@coins.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
        <%#= text_field_tag "coinID",nil,class: "form-control",value: @trigger["coinID"],required: :true%>
      </div>
      <div class="form-group">
        <label for="challengeStatus">challengeStatus</label>
        <%= select_tag 'challengeStatus', options_for_select(@status_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
        <%#= text_field_tag "challengeStatus",nil,class: "form-control",value: @trigger["challengeStatus"],required: :true%>
      </div>
      <div class="form-group">
        <label for="tags">tags</label>
        <%#= text_field_tag "tags",nil,class: "form-control",value: @trigger["tags"],required: :true%>
        <%= select_tag 'tags', options_for_select(@tags.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div class="form-group">
        <label for="amountCoinsReward">amountCoinsReward</label>
        <%= text_field_tag "amountCoinsReward",nil,class: "form-control",value: @trigger["amountCoinsReward"],required: :true%>
      </div>
      <div class="form-group">
        <label for="numberOfRepeat">numberOfRepeat</label>
        <%= select_tag 'numberOfRepeat', options_for_select(@repeat_amounts.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true%>
        <%#= text_field_tag "numberOfRepeat",nil,class: "form-control",value: @trigger["numberOfRepeat"],required: :true%>
      </div>
      <%= submit_tag "Update Trigger",class: "btn btn-primary"%>
      <%= link_to "Back",dashboard_path,class: "btn btn-warning"%>
    <%end%>
  </div>
</div>
<br><br>

<script type="text/javascript">
  $(document).ready(function(){
    $('.trigger_datepicker').datepicker({
      format: 'yyyy-mm-dd'
    });
  });
</script>

app/views/challanges/get_coin_type.js.erb
<% if params[:type].eql?("Coin")%>
	$("#cointypename").html("<%= j(render 'get_coin_type')%>")
<%elsif params[:type].eql?("coinTypeObject")%>
	$("#cointypeobjectname").html("<%= j(render 'get_coin_type')%>")
<%else%>
	$("#rewardcointypename").html("<%= j(render 'get_coin_type')%>")
<%end%>

app/views/challanges/new.html.erb
<div class="container">
  <div class="col-md-10">
    <h3>New Trigger</h3>
    <%= form_tag trigger_create_challanges_path,method: "post" do %>
      <div class="form-group">
        <label for="period">period</label>
        <%= text_field_tag "period",nil,class: "form-control",required: :true,placeholder: "ex: 10"%>
      </div>
      <div class="form-group">
        <label for="actionName">actionName</label>
        <%= text_field_tag "actionName",nil,class: "form-control",required: :true,placeholder: "ex: GPS"%>
      </div>
      <div class="form-group">
        <label for="expiryDate">expiryDate</label>
        <%= text_field_tag "expiryDate",nil,class: "trigger_datepicker form-control",required: :true,autocomplete: :off%>
      </div>
      <div class="form-group">
        <label for="rewardCoinTypeID">rewardCoinTypeID</label>
        <%= select_tag 'rewardCoinTypeID', options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div id="rewardcointypename">
        <div class="form-group">
          <label for="rewardCoinTypeName">rewardCoinTypeName</label>
          <%= text_field_tag "rewardCoinTypeName",nil,class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <label for="coinTypeID">coinTypeID</label>
        <%= select_tag 'coinTypeID', options_for_select(@coin_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div id="cointypename">
        <div class="form-group">
          <label for="coinTypeName">coinTypeName</label>
          <%= text_field_tag "coinTypeName",nil,class: "form-control"%>
        </div>
      </div>
      <div class="form-group">
        <label for="creatorID">creatorID</label>
        <%= text_field_tag "creatorID",nil,class: "form-control",value: @user["objectId"],readonly: true%>
      </div>
      <div class="form-group">
        <label for="coinID">coinID</label>
        <%= select_tag 'coinID', options_for_select(@coins.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div class="form-group">
        <label for="groupName">groupName</label>
        <%= text_field_tag "groupName",nil,class: "form-control",required: :true,placeholder: "ex: Tokyo"%>
      </div>
      <div class="form-group">
        <label for="challengeStatus">challengeStatus</label>
        <%= select_tag 'challengeStatus', options_for_select(@status_types.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
      </div>
      <div class="form-group">
        <label for="tags">tags</label>
        <%= select_tag 'tags', options_for_select(@tags.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true %>
        <%#= text_field_tag "tags",nil,class: "form-control",required: :true,placeholder: "ex: #seven"%>
      </div>
      <div class="form-group">
        <label for="amountCoinsReward">amountCoinsReward</label>
        <%= text_field_tag "amountCoinsReward",nil,class: "form-control",required: :true,placeholder: "ex: 20"%>
      </div>
      <div class="form-group">
        <label for="numberOfRepeat">numberOfRepeat</label>
        <%= select_tag 'numberOfRepeat', options_for_select(@repeat_amounts.collect{ |u| u}),prompt: "Select",class: "form-control",required: :true%>
      </div>
      <%= submit_tag "Create Trigger",class: "btn btn-primary"%>
      <%= link_to "Back",dashboard_path,class: "btn btn-warning"%>
    <%end%>
  </div>
</div>
<br><br>

<script type="text/javascript">
  $(document).ready(function(){
    $('.trigger_datepicker').datepicker({
      format: 'yyyy-mm-dd'
    });
  });
</script>

app/views/challanges/show.html.erb
<div class="container">
	<h3>Trigger</h3>
	<p>
		<strong>ObjectId:</strong>
		<%= @trigger["objectId"]%>
	</p>
	<p>
		<strong>period:</strong>
		<%= @trigger["period"]%>
	</p>
	<p>
		<strong>actionName:</strong>
		<%= @trigger["actionName"]%>
	</p>
	<p>
		<strong>expiryDate:</strong>
		<%= (@trigger["expiryDate"]).to_time.strftime("%d %b %Y")%>
	</p>
	<p>
		<strong>rewardCoinTypeName:</strong>
		<%= @trigger["rewardCoinTypeName"]%>
	</p>
	<p>
		<strong>coinTypeID:</strong>
		<%= @trigger["coinTypeID"]%>
	</p>

	<p>
		<strong>creatorID:</strong>
		<%= @trigger["creatorID"]%>
	</p>
	<p>
		<strong>groupName:</strong>
		<%= @trigger["groupName"]%>
	</p>
	<p>
		<strong>coinID:</strong>
		<%= @trigger["coinID"]%>
	</p>
	<p>
		<strong>rewardCoinTypeID:</strong>
		<%= @trigger["rewardCoinTypeID"]%>
	</p>
	<p>
		<strong>challengeStatus:</strong>
		<%= @trigger["challengeStatus"]%>
	</p>
	<p>
		<strong>tags:</strong>
		<%= @trigger["tags"]%>
	</p>
	<p>
		<strong>amountCoinsReward:</strong>
		<%= @trigger["amountCoinsReward"]%>
	</p>
	<p>
		<strong>numberOfRepeat:</strong>
		<%= @trigger["numberOfRepeat"]%>
	</p><br><br>
	<%= link_to "Dashboard",dashboard_path,class: "btn btn-warning"%>
</div>